### ISSUE TITLE
Need major help, just imported emerald onto my site

### ISSUE THREAD

**Issue by FunkyF1ngers** [DD-GitH/emerald-theme-mybb#15]
1. How do I change the text at the top of the screen next to the green diamond to say "Conformity" instead of "Emerald"?

2. How do I edit the space below the thing mentioned above (the area where it says  "Emerald - Demo. A demo for a great theme"
 -I'd like to change the text & add a different background for that

3. How do I change the announcement?

All help is greatly appreciated. Either respond here, message me on my site (conformitygaming.com), or by email : liamisredmond@gmail.com

**I'VE LOOKED FOR INSTRUCTIONS INSIDE OF THE DOWNLOADED FILE OF EMERALD BUT CAN'T FIND ANY**

**Comment by dvddvd300** [comment]
**1. Logo Changing**
First, go to your AdminCP, go to "Templates" page and select the templates group of the _theme >> Header Templates >> header_ :

You'll find the HTML/CSS logo of the theme which is : `<i class="fa fa-diamond"></i>` Emerald 
To change that into an image (which is highly not recommended because of margin & height problems), replace that to : `<img src="YOUR IMAGE LINK" />`
To keep an HTML/CSS logo, change into any text, for example "_BestForums_". If you want to add a font icon for that (as our logo) please check here. For example `<i class="fa fa-diamond"></i>` means diamond icon.

**2. Header Block**
Go to your AdminCP, go to "Templates" page and select the templates _group of the theme >> Header Templates >> header_ :

You'll find the title which is : `Emerald - Demo`
And the description : `A demo forum for a great theme`
You just have to change the text into whatever you want

**3. Sidebars** 
Go to _Templates >> Emerald Templates >> Index Page Templates >> index_ :
```
<table style="" class="tborder" border="0" cellpadding="{$theme['tablespace']}" cellspacing="{$theme['borderwidth']}">
<tbody><tr>
   <td style="font-weight: bold;" class="thead">
  <i class="fa fa-bullhorn"></i> Announcements 
   </td>
</tr>

<tr>
   <td class="trow2" style="padding:11px">
      <a href="#">This is an example !</a>
   </td>
</tr>
</tbody></table>
```
To add an announcement (with link), search for the past code, the first link is : `<a href="#">This is an example !</a>`, as a first link you can edit the text and replace "#" with your link.
To add another link, add after that (for example) : `<br><a href="YOUR LINK">THE TEXT</a>`

**I hope it helped you**
