### ISSUE TITLE
Mobile Friendly

### ISSUE THREAD

**Issue by eeradptin** [DD-GitH/emerald-theme-mybb#18]
please make this theme mobile friendly. I found this template really good. But when i see post it is not properly visible. 
My website entrepreneurera.in/forum

**Comment by dvddvd300** [comment]
**Error for mobile devices**
![image](https://user-images.githubusercontent.com/21372070/32202330-98130b38-bda1-11e7-8847-420b960da966.png)

**Comment by eeradptin** [comment]
How to disable it then?

**Comment by DD-GitH** [comment]
Do you get an error using mobile register or about theme ?
If it's an error, then try the v1.5 because i fixed a cookie problem that might be the cause of it. Otherwise, this theme is still in improvement and it's not a paid premium theme so we take our time for support, the big favour first of all is giving such awesome theme as gift for mybb users.

**Comment by VRRP-Hero** [comment]
I have the same issue as @dvddvd300.

@DD-GitH How do you disable this? 

I want to be able to show the whole forums via mobile for the mobile users. @eeradptin

**Comment by dvddvd300** [comment]
@VRRP-Hero  
I think it can be solved by changing a bit of the template
```
<div style="float: left;">
<!-- code of the left side of the register form -->
</div>
```
and
```
<div style="float: right;">
<!-- code of the right side of the registration form -->
</div>
```

**or make the width 50% if it is more than Xpx**
